### ISSUE TITLE
Conversion Request: Quake III Arena

### ISSUE THREAD

**Issue by optimus-code** [rds1983/Sichem#2]
Hi there. I noticed you mentioned you take requests as this conversion takes a bit of preparation. I am highly interested in porting Quake III arena to C# from C (There is some assembly which can be ignored/recreated manually) but most of the source is in C, around 200k lines of code. There wouldn't be a need to port the Radiant editor code which is CPP, just the engine.

If this is something you'd be interested in, I'd also be happy to remunerate for the effort put in. (Albeit i'm not made of money so it would be modest)

https://github.com/id-Software/Quake-III-Arena this is the official repo if you are interested.

Regards
Optimus

**Comment by rds1983** [comment]
I dont take money for such services.
However transpiling 200k lines of code is a lot of work. So it's very unlikely that I'll take this job.
Btw, you may try it yourself. I know one case when someone(other than me) managed to figure out how Sichem works: https://github.com/TechnologicalPizza/ZlibSharp

**Comment by optimus-code** [comment]
Hey thanks for the quick response. I know it was a long shot but worth a try.

Am I right in thinking Sichem can do a basic syntax conversion out of the box? If that's the case it would be really helpful for my use case.

**Comment by rds1983** [comment]
Yes, it can. I'd recommend taking a look into various projects transpiled with Sichem(including ZlibSharp that I referenced above) in order to learn how to work with it.
