### ISSUE TITLE
Microsoft Sam

### ISSUE THREAD

**Issue by 4wincode** [rds1983/Sichem#6]
Would you be able to convert this? https://github.com/s-macke/SAM

**Comment by rds1983** [comment]
Here you go: https://github.com/rds1983/SamSharp

**Comment by rds1983** [comment]
Here's example of its work: https://youtu.be/-zd9w1wQk9E

**Comment by 4wincode** [comment]
Thank you so much for porting that over! One question though, I'm not sure if there's an actual issue or if it's just my PC but the monogame test program seems to crash every time I try to enter pretty much anything other than the default.

**Comment by rds1983** [comment]
I havent experienced anything like that.
Just tested it with "Commodore 64 is best gaming platform!" and it works fine.
It's important to note that you can't enter more than 255 characters.
Anyway if you want that being addressed, create the corresponding issue at SamSharp and describe what parameters you enter and what type of Exception is being thrown.
