### ISSUE TITLE
Source code is missing ConstantsUtility.cs

### ISSUE THREAD

**Issue by gchoquet** [rds1983/Sichem#7]
Also needs references to libclang.dll and sealang.dll, apparently from other repositories by rds1983.

**Comment by rds1983** [comment]
Sichem is superceded by [Hebron](https://github.com/HebronFramework/Hebron)
The latter is already used in [StbImageSharp](https://github.com/StbSharp/StbImageSharp), [StbTrueTypeSharp](https://github.com/StbSharp/StbTrueTypeSharp) and [stb_image_rust](https://github.com/StbRust/stb_image_rust).

I am going to make Sichem archived soon.
